services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - app
    container_name: app_nginx
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      retries: 3
    networks:
      - app_network

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "${DB_PORT}:5432"
    networks:
      - app_network

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: app
    depends_on:
      - db
    command: /bin/sh -c "chmod -R 775 /var/www/storage /var/www/bootstrap/cache && php-fpm"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge